name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      CUSTOM_IMAGE_NAME: ${{ secrets.CUSTOM_IMAGE_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set image name (force lowercase)
        run: |
          if [ -n "$CUSTOM_IMAGE_NAME" ]; then
            RAW_NAME="${DOCKER_USERNAME}/${CUSTOM_IMAGE_NAME}"
            echo "Using custom image name: $RAW_NAME"
          else
            REPO_NAME=$(basename "$GITHUB_REPOSITORY")
            RAW_NAME="${DOCKER_USERNAME}/${REPO_NAME}"
            echo "Using repository name as image name: $RAW_NAME"
          fi

          # Convert to lowercase
          IMAGE_NAME=$(echo "$RAW_NAME" | tr '[:upper:]' '[:lower:]')
          echo "Final Docker image name: $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Detect version from Git tag
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "Detected version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          echo "Building Docker image: $IMAGE_NAME:$VERSION and $IMAGE_NAME:latest"
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .

      - name: Push Docker images
        run: |
          echo "Pushing image: $IMAGE_NAME:$VERSION"
          docker push $IMAGE_NAME:$VERSION

          echo "Pushing image: $IMAGE_NAME:latest"
          docker push $IMAGE_NAME:latest

      - name: Summary
        run: |
          echo ""
          echo "✅ Docker Image Pushed Successfully!"
          echo "-----------------------------------"
          echo "📦 Image Name : $IMAGE_NAME"
          echo "🏷️  Version    : $VERSION"
          echo "📤 Status     : Pushed"
